// ⚠️ FICHIER AUTO-GÉNÉRÉ — ne pas modifier manuellement
// Modifie CLIENT.md puis relance : npm run sync-client

export const clientConfig = {
  identity: {
    prenomDirigeant: "Khellaf",
    nomDirigeant: "Tikharbatine",
    nomEntreprise: "TK Plomberie",
    nomLegal: "TK PLOMBERIE",
    genreDirigeant: "masculin",
    founder: "Khellaf Tikharbatine",
  },
  contact: {
    telephone: "07 69 98 50 92",
    telephoneHref: "tel:+33769985092",
    telephoneUrgence: "07 69 98 50 92",
    email: "barbierplomberie@free.fr",
    adresse: "42 Avenue Paul Dupont",
    ville: "Livry-Gargan",
    codePostal: "93190",
    departement: "Seine-Saint-Denis",
    region: "Île-de-France",
    zoneIntervention: "Livry-Gargan et 30km autour",
    zoneKm: "30",
  },
  horaires: {
    semaine: "Lun-Ven 8h-19h",
    samedi: "Sam 9h-17h",
    dimanche: "Fermé",
    urgence: "7j/7 24h/24",
  },
  branding: {
    couleurPrimaireHue: "210",
    couleurAccentHue: "30",
  },
  social: {
    facebook: "",
    instagram: "",
    google: "",
  },
  domaine: "tk-plomberie.fr",
  url: "https://www.tk-plomberie.fr",
  legal: {
    siret: "993 011 485 00014",
    rge: "",
    assuranceDecennale: "",
  },
  chiffres: {
    anneesExperience: 10,
    nombreInterventions: 500,
    noteGoogle: 5,
    nombreAvis: 12,
    anneeCreation: 2025,
    delaiIntervention: "moins de 2h",
    disponibilite: "7j/7",
    tauxSatisfaction: "98",
  },
  geo: {
    latitude: "48.9197",
    longitude: "2.5386",
  },
  communes: [
    { name: "Livry-Gargan", postalCode: "93190" },
    { name: "Aulnay-sous-Bois", postalCode: "93600" },
    { name: "Sevran", postalCode: "93270" },
    { name: "Villepinte", postalCode: "93420" },
    { name: "Le Blanc-Mesnil", postalCode: "93150" },
    { name: "Bondy", postalCode: "93140" },
    { name: "Clichy-sous-Bois", postalCode: "93390" },
    { name: "Montfermeil", postalCode: "93370" },
    { name: "Vaujours", postalCode: "93410" },
    { name: "Coubron", postalCode: "93470" },
    { name: "Le Raincy", postalCode: "93340" },
    { name: "Gagny", postalCode: "93220" },
    { name: "Rosny-sous-Bois", postalCode: "93110" },
    { name: "Noisy-le-Grand", postalCode: "93160" },
    { name: "Tremblay-en-France", postalCode: "93290" },
    { name: "Villemomble", postalCode: "93250" },
    { name: "Les Pavillons-sous-Bois", postalCode: "93320" },
    { name: "Neuilly-sur-Marne", postalCode: "93330" },
    { name: "Bobigny", postalCode: "93000" },
    { name: "Drancy", postalCode: "93700" },
  ],
  services: [
    { title: "Dépannage urgent", shortDescription: "Intervention rapide en moins de 2h pour toutes vos urgences plomberie.", description: "Fuite d'eau, canalisation bouchée, dégât des eaux, panne de chaudière... Notre équipe intervient en urgence 7j/7 à Livry-Gargan et dans tout le 93. Diagnostic sur place et réparation immédiate dans la majorité des cas.", icon: "Siren", slug: "/depannage-plomberie" },
    { title: "Plomberie générale", shortDescription: "Installation, remplacement et mise aux normes de vos équipements.", description: "Robinetterie, tuyauterie, raccordements, WC, éviers, recherche de fuite... Nous intervenons pour tous vos travaux de plomberie à Livry-Gargan et en Seine-Saint-Denis, de l'installation neuve à la mise aux normes de vos installations existantes.", icon: "Wrench", slug: "/plomberie" },
    { title: "Salle de bain", shortDescription: "Rénovation complète, douche italienne, adaptation PMR.", description: "De la conception à la réalisation, nous prenons en charge votre projet de rénovation de salle de bain. Douche italienne, remplacement baignoire, accessibilité PMR, meuble vasque... Un interlocuteur unique du début à la fin.", icon: "Bath", slug: "/renovation-salle-de-bain" },
    { title: "Chauffage", shortDescription: "Chaudière, pompe à chaleur, plancher chauffant, entretien annuel.", description: "Installation et remplacement de chaudière gaz condensation, pompe à chaleur air-eau, plancher chauffant, radiateurs. Entretien annuel obligatoire et dépannage de votre système de chauffage.", icon: "Flame", slug: "/chauffage" },
    { title: "Chauffe-eau", shortDescription: "Remplacement, ballon thermodynamique, détartrage.", description: "Remplacement de chauffe-eau électrique ou gaz, installation de ballon thermodynamique pour réduire votre facture énergétique. Détartrage et entretien pour prolonger la durée de vie de votre équipement.", icon: "Droplets", slug: "/chauffe-eau" },
    { title: "Entretien", shortDescription: "Contrats d'entretien chaudière et maintenance préventive.", description: "L'entretien annuel de votre chaudière est obligatoire. Nous proposons des contrats d'entretien incluant la visite annuelle, le dépannage prioritaire et les pièces d'usure.", icon: "ClipboardCheck", slug: "/chauffage#entretien" },
  ],
  testimonials: [
    { name: "Marie L.", rating: 5, text: "Intervention très rapide pour une fuite sous l'évier. Khellaf est arrivé en moins d'une heure, travail propre et prix correct. Je recommande !", date: "Déc 2025", source: "Google" },
    { name: "Sébastien D.", rating: 5, text: "Excellent plombier, très professionnel. Remplacement de mon chauffe-eau fait dans la journée. Ponctuel et soigneux.", date: "Jan 2026", source: "Google" },
    { name: "Fatima B.", rating: 5, text: "Rénovation complète de ma salle de bain. Résultat magnifique, dans les délais et le budget annoncé. Merci TK Plomberie !", date: "Nov 2025", source: "Google" },
    { name: "Jean-Pierre M.", rating: 4, text: "Bon travail pour le débouchage de mes canalisations. Seul petit bémol, un léger retard le jour de l'intervention, mais le résultat est impeccable.", date: "Jan 2026", source: "Google" },
    { name: "Sophie R.", rating: 5, text: "J'ai fait appel à TK Plomberie pour l'installation d'une douche italienne. Travail soigné, finitions parfaites. Un vrai artisan.", date: "Déc 2025", source: "Google" },
    { name: "Karim A.", rating: 5, text: "Dépannage en urgence un dimanche pour une fuite importante. Réactif, efficace et honnête sur les tarifs. Plombier de confiance.", date: "Nov 2025", source: "Google" },
    { name: "Isabelle C.", rating: 5, text: "Entretien annuel de ma chaudière gaz réalisé avec sérieux. Explications claires sur l'état de l'installation. Très satisfaite.", date: "Jan 2026", source: "Google" },
    { name: "Thomas G.", rating: 4, text: "Installation d'un robinet thermostatique dans la douche. Travail bien fait, tarif raisonnable. Petit délai d'attente pour le rendez-vous mais ça valait le coup.", date: "Déc 2025", source: "Google" },
    { name: "Nadia H.", rating: 5, text: "Merci pour le remplacement rapide de mon ballon d'eau chaude qui avait lâché. Intervention le jour même, installation propre et conseils utiles.", date: "Jan 2026", source: "Google" },
    { name: "Philippe V.", rating: 5, text: "Plombier sérieux et compétent. A résolu un problème de fuite que deux autres plombiers n'avaient pas réussi à trouver. Je ne ferai plus appel qu'à lui.", date: "Nov 2025", source: "Google" },
  ],
  admin: {
    password: "1234",
  },
  seo: {
    metaTitleAccueil: "Plombier Livry-Gargan — TK Plomberie | Dépannage 7j/7",
    metaDescAccueil: "Plombier chauffagiste à Livry-Gargan (93190). Dépannage urgent 7j/7, installation, rénovation salle de bain, chauffage. Devis gratuit. Appelez le 07 69 98 50 92.",
    descriptionEntreprise: "TK Plomberie, votre plombier chauffagiste à Livry-Gargan et en Seine-Saint-Denis (93). Dépannage urgent 7j/7, installation, rénovation salle de bain, chauffage. Devis gratuit.",
    slogan: "Votre plombier à Livry-Gargan — Dépannage 7j/7, intervention rapide",
  },
} as const;

export type ClientConfig = typeof clientConfig;
